service: fauna-serverless-v2

frameworkVersion: '3'

# Specify donenv
useDotenv: true

# Add Fauna Plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-fauna

fauna:
  client:
    secret: ${env:FAUNA_ROOT_KEY}
    domain: db.us.fauna.com
  collections:
    Books: 
      name: Books

provider:
  name: aws
  runtime: nodejs12.x
  httpApi:
    cors: true

# Define lambdas
functions:
  book:
    handler: handler.book 
    events:
      - httpApi:
          path: /books/{id}
          method: get
  createBook:
    handler: handler.createBook
    events:
      - httpApi:
          path: /books
          method: post
  deleteBook:
    handler: handler.deleteBook
    events:
      - httpApi:
          path: /books/{id}
          method: delete
  updateBook:
    handler: handler.updateBook
    events:
      - httpApi:
          path: /books/{id}
          method: put
  
